# Generated by Django 5.1.2 on 2024-11-22 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hurdlethon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='NICKNAME',
            new_name='nickname',
        ),
    ]
