# Generated by Django 5.1.3 on 2024-11-19 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hurdlethon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='ANSWER_ID',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='LECTURE_ID',
        ),
    ]
