# Generated by Django 5.1.3 on 2024-11-27 05:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hurdlethon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='verification_code',
            field=models.IntegerField(),
        ),
    ]
