# Generated by Django 5.1.2 on 2024-11-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hurdlethon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.JSONField(blank=True, default=[], verbose_name='관심 있는 과목'),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_point',
            field=models.PositiveIntegerField(default=0, verbose_name='점수 총점'),
        ),
    ]
