# Generated by Django 5.1.2 on 2024-11-22 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hurdlethon', '0002_rename_nickname_user_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nickname',
            new_name='NICKNAME',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='USER_ID',
        ),
    ]
