# Generated by Django 5.1.2 on 2024-11-26 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hurdlethon', '0003_rename_curious_question_curious_count_curious'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='like',
            new_name='like_count',
        ),
    ]
