# Generated by Django 5.1.3 on 2024-11-24 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hurdlethon', '0004_rename_answer_id_answer_answer_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'verbose_name': '강의'},
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='name',
            new_name='lecture_name',
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lecture_day',
            field=models.CharField(help_text='월~일 (7자리 이진수)', max_length=7, verbose_name='강의 요일'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='semester',
            field=models.CharField(default='1', max_length=1, verbose_name='학기'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='year',
            field=models.CharField(default='2024', max_length=4, verbose_name='년도'),
        ),
        migrations.AlterField(
            model_name='question',
            name='lecture_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='hurdlethon.lecture', verbose_name='강의'),
        ),
        migrations.AlterModelTable(
            name='lecture',
            table='lecture',
        ),
    ]
