# Generated by Django 5.1.3 on 2024-11-24 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hurdlethon', '0005_alter_lecture_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='hurdlethon.question'),
        ),
    ]
