# Generated by Django 5.1.3 on 2024-11-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hurdlethon', '0007_emailverification_remove_user_expiration_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='verification_code',
            field=models.IntegerField(max_length=6),
        ),
    ]
